=== ESIPFed/lod/resources/ontology/agu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.agu.org/focus_group/essi/schema"
  targetNamespace="http://www.agu.org/focus_group/essi/schema" elementFormDefault="qualified"> 
  <xs:element name="AGUAbstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Meeting" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Section" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Id" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Keywords" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Keyword" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Abstract" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Session" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Hour" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Authors" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Author" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="Email" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Affiliations" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Affiliation" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>				
                  </xs:sequence>
                </xs:complexType>
              </xs:element>					
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ESIPFed/lod/resources/data/xml/2008_Fall_Meeting_IN21C-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2008 Fall Meeting</Meeting>
  <Section>Earth and Space Informatics [IN]</Section>
  <Id>IN21C-02</Id>
  <Keywords>
    <Keyword>0300  ATMOSPHERIC COMPOSITION AND STRUCTURE</Keyword>
    <Keyword>0400  BIOGEOSCIENCES</Keyword>
    <Keyword>0500  COMPUTATIONAL GEOPHYSICS</Keyword>
    <Keyword>1800  HYDROLOGY</Keyword>
    <Keyword>2100  INTERPLANETARY PHYSICS</Keyword>
  </Keywords>
  <Abstract>Ever increasing model resolutions and physical processes in climate models demand continual computing power increases. The IBM Cell processor&apos;s order-of- magnitude peak performance increase over conventional processors makes it very attractive for fulfilling this requirement. However, the Cell&apos;s characteristics: 256KB local memory per SPE and the new low-level communication mechanism, make it very challenging to port an application. We selected the solar radiation component of the NASA GEOS-5 climate model, which: (1) is representative of column physics components (~50% total computation time), (2) has a high computational load relative to data traffic to/from main memory, and (3) performs independent calculations across multiple columns. We converted the baseline code (single-precision, Fortran code) to C and ported it to an IBM BladeCenter QS20, manually SIMDizing 4 independent columns, and found that a Cell  with 8 SPEs can process more than 3000 columns per second.  Compared with the baseline results, the Cell is ~6.76x, ~8.91x, ~9.85x faster than a core on Intel&apos;s Xeon Woodcrest, Dempsey, and Itanium2 respectively. Our analysis shows that the Cell could also speed up the dynamics component (~25% total computation time). We believe this dramatic performance improvement makes the Cell processor very competitive, at least  as an accelerator. We will report our experience in porting both the C and Fortran codes and will discuss our  work in porting other climate model components.</Abstract>
  <Title>Accelerate Climate Models with the IBM Cell Processor</Title>
  <Session>IN21C</Session>
  <Hour>08:15h</Hour>
  <Authors>
    <Author><Name>Zhou, S</Name><Email>shujia.zhou@nasa.gov</Email><Affiliations><Affiliation>Northrop Grumman Corporation, 4801 Stonecroft Blvd., Westfields, VA 20151, United States</Affiliation><Affiliation>NASA Goddard Science Flight Center, Code 610, Greenbelt, MD 20771, United States</Affiliation></Affiliations></Author>
    <Author><Name>Duffy, D</Name><Email>daniel.q.duffy@nasa.gov</Email><Affiliations><Affiliation>Computer Sciences Corporation, 3170 Fairview Park Drive, Falls Church, VA 22042, United States</Affiliation><Affiliation>NASA Goddard Science Flight Center, Code 610, Greenbelt, MD 20771, United States</Affiliation></Affiliations></Author>
    <Author><Name>Clune, T</Name><Email>tom.clune@nasa.gov</Email><Affiliations><Affiliation>NASA Goddard Science Flight Center, Code 610, Greenbelt, MD 20771, United States</Affiliation></Affiliations></Author>
    <Author><Name>Williams, S</Name><Email>samw@EECS.Berkeley.EDU</Email><Affiliations><Affiliation>University of California, Berkeley, Dept. of Electrical Eng. and Computer Science, Berkeley, CA 94720, United States</Affiliation></Affiliations></Author>
    <Author><Name>Suarez, M</Name><Email>max.j.suarez@nasa.gov</Email><Affiliations><Affiliation>NASA Goddard Science Flight Center, Code 610, Greenbelt, MD 20771, United States</Affiliation></Affiliations></Author>
    <Author><Name>Halem, M</Name><Email>halem@umbc.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2009_Joint_Assembly_IN31B-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2009 Joint Assembly</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN31B-02</Id>
  <Keywords>
    <Keyword>0599  General or miscellaneous</Keyword>
  </Keywords>
  <Abstract>This presentation will briefly discuss the different perspectives that characterize the main geo-spatial Communities as far as the coverage data model is concerned. Then, it will present the results of a user requirements analysis for an effective coverage access service conceived to serve the use scenarios of the Earth and Space Science Community. Eventually, possible new categories of access services are described comparing them with the existing service implementations. The coverage concept was defined by the ISO 19123 to summarise the different conceptual and physical representations of an image, going further by enlarging the variety of geospatial information that can be represented this way. In fact, a coverage is a feature that has multiple values for each attribute type, where each  direct position within the geometric representation of the feature has a single value for each attribute type. The coverage concept generalizes and extends the raster structure type by referring to any data representation that assigns values directly to spatial positions -regularly and non-regularly distributed. In fact, a coverage associates a position within a domain (commonly, spatial-temporal domain) to a value of a defined data type. Hence, it realizes a function (namely, coverage function) from a domain to an attribute domain -i.e. the co- domain or coverage range. Just as the concepts of discrete and continuous phenomena are not mutually exclusive, their representations as discrete features or coverages are not mutually exclusive. The same phenomenon may be represented as either a discrete feature or a coverage. However, coverages are the prevailing data structures in Earth and Space Science community. The analysis of software requirements for coverage access services was made adopting two methods concurrently the Critical Success Factor (CSF) analysis method, which was supplemented by the Usage Cases analysis. This methodology was chosen by the W3C for the Web Services Architecture analysis. The CSF Analysis methodology is a top-down means of determining requirements based on the needs of the organization while the Use Case approach implements a bottom-up methodology collecting users&apos; requirements. The respective results were cross-referenced to ensure consistency. The vast majority of use cases are taken from the work of the OGC GALEON Working Group in the coverage domain. Mainly, GALEON use cases are stemming from the meteo-ocean community, or Fluid Earth Science (FES); however, they appear to cover most of the requirements characterizing the overall Earth and Space Science community.</Abstract>
  <Title>overage Access Services for Earth and Space Sciences: Requirements Analysis</Title>
  <Session>IN31B</Session>
  <Hour>08:20h</Hour>
  <Authors>
    <Author><Name>Nativi, S</Name><Email>nativi@imaa.cnr.it</Email><Affiliations><Affiliation>University of Florence at Prato, Piazza Ciardi 25, Prato, 59100, Italy</Affiliation><Affiliation>Italian National Rsearch Council (CNR-IMAA), Piazza Ciardi 25, Prato, 59100, Italy</Affiliation></Affiliations></Author>
    <Author><Name>Domenico, B</Name><Email>Ben@unidata.ucar.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/Fall_Meeting_2005_IN31B-1157.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>Fall Meeting 2005</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN31B-1157</Id>
  <Keywords>
    <Keyword>7599  General or miscellaneous</Keyword>
    <Keyword>7899  General or miscellaneous</Keyword>
    <Keyword>9820  Techniques applicable in three or more fields</Keyword>
  </Keywords>
  <Abstract>What is the best way to move data from point A to point B? That all depends on what connects the two points and what kind of data you are trying to move. Selecting the right technology requires a careful consideration of the problem, an awareness of existing solutions and knowledge of appropriate standards. When moving a solution through the design, implementation and deployment stages there are a variety of development methods. Matching the development method to the scale of the task is important. Some of the technology challenges that the science community must address overlap with our commercial counterparts. However, there are some technology challenges which are unique to science and require new and innovative approaches. Based on our experience developing solutions for NASA&apos;s Planetary Data System (PDS), Dawn Science Center, and the  Space Physics Archive Search and Extract (SPASE) project we have considerable experience in what does and does not work. We present an assessment of the adoption threshold of selected standards, technology and development methods. We will discuss how changing expectations and evolving requirements impact the effectiveness of chosen solutions.</Abstract>
  <Title>The Buzzword Puzzle: Finding the Right Technology for the Problem</Title>
  <Session>IN31B</Session>
  <Hour>0800h</Hour>
  <Authors>
    <Author><Name>King, T A</Name><Email>tking@igpp.ucla.edu</Email><Affiliations><Affiliation>Institute of Geophysics and Planetary Physics, UCLA, 3846 Slichter Hall, Los Angeles, CA 9009-1567</Affiliation></Affiliations></Author>
    <Author><Name>Walker, R J</Name><Email>rwalker@igpp.ucla.edu</Email><Affiliations><Affiliation>Institute of Geophysics and Planetary Physics, UCLA, 3846 Slichter Hall, Los Angeles, CA 9009-1567</Affiliation></Affiliations></Author>
    <Author><Name>Joy, S P</Name><Email>sjoy@igpp.ucla.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2007_Fall_Meeting_IN21C-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2007 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN21C-02</Id>
  <Keywords>
    <Keyword>3000  MARINE GEOLOGY AND GEOPHYSICS</Keyword>
    <Keyword>3040  Plate tectonics</Keyword>
    <Keyword>3060  Subduction zone processes</Keyword>
    <Keyword>8150  Plate boundary: general</Keyword>
  </Keywords>
  <Abstract>The international geoscience community is engaged in scientifically aligned goals to understand the fundamental  processes of crustal formation, modification and destruction at the Earth&apos;s plate boundaries through broad multi- disciplinary initiatives such as the InterRidge and InterMARGINS programs. These programs involve the collection  of unique data sets during oceanic and terrestrial expeditions and subsequent laboratory work conducted by research institutions around the globe. These international research efforts would benefit significantly if data collections maintained as national efforts could be better linked and broader access were initiated. At present there are no formal agreements within these programs for data sharing between foreign partners. A workshop was convened in May 2007, jointly sponsored and funded by MARGINS, InterMARGINS, InterRidge, Ridge2000, the US National Science Foundation, and the German project &quot;The Future Ocean&quot;, to explore current opportunities and challenges for international data exchange to support marine geoscience research broadly. Participants from 14 countries discussed technological, organizational, and cultural issues for building a global data network and agreed on a set of recommendations regarding science user needs, data documentation, data publication, metadata interoperability, and opportunities and obstacles for international data sharing. They underscored that (1) open public access to data is fundamental to verifiable scientific progress; (2) uniform best practices and standards for data acquisition, data submission to data centers, and data publication need to be developed and used routinely within the international community, facilitated by tools that automate metadata acquisition in the field and in the lab; (3) the proliferation of metadata standards needs to be minimized to achieve  a uniform approach for scientific metadata building upon the work of existing community-based projects; (4) data centers should expose their data resources via web services to enable data access through programmatic interfaces and expand options for data analysis and visualization; (5) international programs and bodies such as GEOSS, eGY, and ICSU should be leveraged to promote an initiative for a global data network; (6) a dedicated task group is needed to advance the implementation of a global data network along with special interest groups to share experience and solutions on issues concerning metadata and interfaces. Several immediate next steps were identified to initiate the implementation of these recommendations.</Abstract>
  <Title>Building a Global Data Network for Studies of Earth Processes at the World&apos;s Plate Boundaries</Title>
  <Session>IN21C</Session>
  <Hour>08:20h</Hour>
  <Authors>
    <Author><Name>Lehnert, K A</Name><Email>lehnert@ldeo.columbia.edu</Email><Affiliations><Affiliation>Lamont-Doherty Earth Observatory of Columbia University, 61 Route 9W, Palisades, NY 10964, United States</Affiliation></Affiliations></Author>
    <Author><Name>Carbotte, S</Name><Email>carbotte@ldeo.columbia.edu</Email><Affiliations><Affiliation>Lamont-Doherty Earth Observatory of Columbia University, 61 Route 9W, Palisades, NY 10964, United States</Affiliation></Affiliations></Author>
    <Author><Name>Tsuboi, S</Name><Email>tsuboi@jamstec.go.jp</Email><Affiliations><Affiliation>Japan Agency for Marine-Earth Science and Technology JAMSTEC, 3173-25 Showa-machi,  Kanazawa-ku, Yokohama, 236-0001, Japan</Affiliation></Affiliations></Author>
    <Author><Name>Weinrebe, W</Name><Email>wweinrebe@ifm-geomar.de</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2006_Joint_Assembly_IN33A-05.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2006 Joint Assembly</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN33A-05</Id>
  <Keywords>
    <Keyword>3367  Theoretical modeling</Keyword>
    <Keyword>3300  ATMOSPHERIC PROCESSES</Keyword>
    <Keyword>3329  Mesoscale meteorology</Keyword>
  </Keywords>
  <Abstract>A model  intercomparison program involving a large number of academic and operational institutions has been implemented in South America since 2003, motivated by the SALLJEX Intercomparison Program in 2003 (a research program focused on the identification of the role of the Andes low level jet moisture transport from the Amazon to the Plata basin) and the WMO/THORPEX (www.wmo.int/thorpex) goals to improve predictability through the proper combination of numerical weather forecasts. This program also explores the potential predictability associated with the combination of a large number of possible scenarios in the time scale of a few days to up to 15 days. Five academic institutions and five operational forecasting centers  in several countries in South America, 1 academic institution in the USA, and the main global forecasting centers (NCEP, UKMO, ECMWF) agreed to provide numerical products based on operational and experimental models. The metric for model validation is concentrated on the fit of the forecast to surface observations. Meteorological data from airports, synoptic stations operated by national weather services, automatic data platforms maintained by different institutions, the PIRATA buoys etc are all collected through LDM/NCAR or direct transmission. Approximately 40 models outputs are available on a daily basis, twice a day.  A simple procedure based on data assimilation principles was quite successful in combining the available forecasts in order to produce temperature, dew point, wind, pressure and precipitation forecasts at station points in S. America. The procedure is based on removing each model bias at the observational point and a weighted average based on the mean square error of the forecasts. The base period for estimating the bias and mean square error is of the order of 15 to 30 days. Products of the intercomparison model program and the optimal statistical combination of the available forecasts are public and available in real time (www.master.iag.usp.br/). Monitoring of the use of the products reveal a growing trend in the last year (reaching about 10.000 accesses per day in recent months).  The intercomparison program provides a rich data set for educational products (real time use in Synoptic Meteorology and Numerical Weather Forecasting lectures), operational weather forecasts in national or regional weather centers and for research purposes. During the first phase of the program it was difficult to convince potential participants to share the information in the public homepage. However, as the system evolved, more and more institutions became associated with  the program.  The general opinion of the participants is that the system provides an unified metric for evaluation, a forum for discussion of the physical origin of the model forecast differences and therefore improvement of the quality of the numerical guidance.</Abstract>
  <Title>Benefits of Sharing Information:  Supermodel Ensemble and Applications in South                           America</Title>
  <Session>IN33A</Session>
  <Hour>15:10h</Hour>
  <Authors>
    <Author><Name>Dias, P L</Name><Email>pldsdias@master.iag.usp.br</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2009_Fall_Meeting_IN34A-07.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2009 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics</Section>
  <Id>IN34A-07</Id>
  <Keywords>
    <Keyword>HYDROLOGY / Precipitation-radar</Keyword>
    <Keyword>INFORMATICS / Real-time and responsive information delivery</Keyword>
    <Keyword>INFORMATICS / Visualization and portrayal</Keyword>
    <Keyword>INFORMATICS / Workflow</Keyword>
  </Keywords>
  <Abstract>Urban flooding is responsible for the loss of life and property as well as the release of pathogens and other pollutants into the environment. Previous studies have shown that spatial distribution of intense rainfall significantly impacts the triggering and behavior of urban flooding. However, no general purpose tools yet exist for deriving rainfall data and rendering them in real-time at the resolution of hydrologic units used for analyzing urban flooding. This paper presents a new visual analytics system that derives and renders rainfall data from the NEXRAD weather radar system at the sewershed (i.e. urban hydrologic unit) scale in real-time for a Chicago stormwater management project. We introduce a lightweight Web 2.0 approach which takes advantages of scientific workflow management and publishing capabilities developed at NCSA (National Center for Supercomputing Applications), streaming data-aware semantic content management repository, web-based Google Earth/Map and time-aware KML (Keyhole Markup Language). A collection of polygon-based virtual sensors is created from the NEXRAD Level II data using spatial, temporal and thematic transformations at the sewershed level in order to produce persistent virtual rainfall data sources for the animation. Animated color-coded rainfall map in the sewershed can be played in real-time as a movie using time-aware KML inside the web browser-based Google Earth for visually analyzing the spatiotemporal patterns of the rainfall intensity in the sewershed. Such system provides valuable information for situational awareness and improved decision support during extreme storm events in an urban area. Our further work includes incorporating additional data (such as basement flooding events data) or physics-based predictive models that can be used for more integrated data-driven decision support.</Abstract>
  <Title>Data-Driven Geospatial Visual Analytics for Real-Time Urban Flooding Decision Support</Title>
  <Session>IN34A</Session>
  <Hour>1730h</Hour>
  <Authors>
    <Author><Name>Liu, Y</Name><Email>yongliu@ncsa.uiuc.edu</Email><Affiliations><Affiliation>National Center for Supercomputing Applications (NCSA), University of Illinois at Urbana-Champaign, Urbana, IL, United States</Affiliation></Affiliations></Author>
    <Author><Name>Hill, D</Name><Email>djhill1@illinois.edu</Email><Affiliations><Affiliation>Civil and Environmental Engineering, Rutgers University, Piscataway, NJ, United States</Affiliation></Affiliations></Author>
    <Author><Name>Rodriguez, A</Name><Email>alejandr@ncsa.illinois.edu</Email><Affiliations><Affiliation>National Center for Supercomputing Applications (NCSA), University of Illinois at Urbana-Champaign, Urbana, IL, United States</Affiliation></Affiliations></Author>
    <Author><Name>Marini, L</Name><Email>lmarini@ncsa.illinois.edu</Email><Affiliations><Affiliation>National Center for Supercomputing Applications (NCSA), University of Illinois at Urbana-Champaign, Urbana, IL, United States</Affiliation></Affiliations></Author>
    <Author><Name>Kooper, R</Name><Email>kooper@ncsa.illinois.edu</Email><Affiliations><Affiliation>National Center for Supercomputing Applications (NCSA), University of Illinois at Urbana-Champaign, Urbana, IL, United States</Affiliation></Affiliations></Author>
    <Author><Name>Myers, J</Name><Email>jimmyers@ncsa.illinois.edu</Email><Affiliations><Affiliation>National Center for Supercomputing Applications (NCSA), University of Illinois at Urbana-Champaign, Urbana, IL, United States</Affiliation></Affiliations></Author>
    <Author><Name>Wu, X</Name><Email>wenzi7@illinois.edu</Email><Affiliations><Affiliation>Civil and Environmental Engineering, University of Illinois at Urbana-Champaign, Urbana, IL, United States</Affiliation></Affiliations></Author>
    <Author><Name>Minsker, B S</Name><Email>minsker@uiuc.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2009_Joint_Assembly_IN31A-08.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2009 Joint Assembly</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN31A-08</Id>
  <Keywords>
    <Keyword>0525  Data management</Keyword>
    <Keyword>0530  Data presentation and visualization</Keyword>
    <Keyword>1819  Geographic Information Systems</Keyword>
  </Keywords>
  <Abstract>This study presents a prototype of database system for managing geological data from the Skarn/Porphyry type  ore deposit. The characteristics of geological data obtained from the Skarn/Porphyry mine development were analyzed and categorized to define the schema of database system such as data fields in tables, the relationships between tables and key index fields to create query functions. The database system was also designed to maintain the digital image data for quantitatively analyzing the discontinuities along the mine tunnel routes. Finally, a prototype of effective database management system that can be used in the mining industry was developed in this study.</Abstract>
  <Title>Development of an Effective Database Management System for the Skarn/Porphyry Type Ore Deposit</Title>
  <Session>IN31A</Session>
  <Hour>0800h</Hour>
  <Authors>
    <Author><Name>Choi, Y</Name><Email>yspower7@snu.ac.kr</Email><Affiliations><Affiliation>Department of Energy Systems Engineering, Seoul National University, Seoul, 151-744, Korea, Republic of</Affiliation></Affiliations></Author>
    <Author><Name>Roh, T</Name><Email>realoptimist@hanmail.net</Email><Affiliations><Affiliation>Department of Energy Systems Engineering, Seoul National University, Seoul, 151-744, Korea, Republic of</Affiliation></Affiliations></Author>
    <Author><Name>Park, H</Name><Email>hpark@snu.ac.kr</Email></Author>
  </Authors>
</AGUAbstract>
