=== ESIPFed/lod/resources/ontology/agu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.agu.org/focus_group/essi/schema"
  targetNamespace="http://www.agu.org/focus_group/essi/schema" elementFormDefault="qualified"> 
  <xs:element name="AGUAbstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Meeting" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Section" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Id" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Keywords" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Keyword" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Abstract" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Session" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Hour" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Authors" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Author" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="Email" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Affiliations" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Affiliation" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>				
                  </xs:sequence>
                </xs:complexType>
              </xs:element>					
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ESIPFed/lod/resources/data/xml/2010_Fall_Meeting_IN21D-03.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2010 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics</Section>
  <Id>IN21D-03</Id>
  <Keywords>
    <Keyword>INFORMATICS / Cyberinfrastructure</Keyword>
    <Keyword>INFORMATICS / Software re-use</Keyword>
    <Keyword>INFORMATICS / Workflow</Keyword>
    <Keyword>INFORMATICS / General or miscellaneous</Keyword>
  </Keywords>
  <Abstract>e-Science and cyberinfrastucture at their outset tended to focus on &amp;#8216;big science&amp;#8217; and cross-organisational infrastructures, demonstrating complex engineering with the promise of high returns. It soon became evident that the key to researchers harnessing new technology for everyday use is a user-centric approach which empowers the user - both from a developer and an end user viewpoint. For example, this philosophy is demonstrated in workflow systems for systematic data processing and in the Web 2.0 approach as exemplified by the myExperiment social web site for sharing workflows, methods and &amp;#8216;research objects&amp;#8217;. Hence the most disruptive aspect of Cloud and virtualisation is perhaps that they make new computational resources and applications usable, creating a flourishing ecosystem for routine processing and innovation alike - and in this we must consider software sustainability. This talk will discuss the changing nature of e-Science digital ecosystem, focus on the e-infrastructure for cross-disciplinary work, and highlight issues in sustainable software development in this context.</Abstract>
  <Title>Towards usable and interdisciplinary e-infrastructure (&lt;i&gt;Invited&lt;/i&gt;)</Title>
  <Session>IN21D</Session>
  <Hour>0838h</Hour>
  <Authors>
    <Author><Name>De Roure, D</Name><Email>david.deroure@oerc.ox.ac.uk</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/Fall_Meeting_2005_IN33A-1169.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>Fall Meeting 2005</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN33A-1169</Id>
  <Keywords>
    <Keyword>4262  Ocean observing systems</Keyword>
  </Keywords>
  <Abstract>Millions of in-situ ocean observations are now available to scientists through the OPeNDAP network protocol. However, there are few Web applications that support the in-situ OPeNDAP protocol and this has limited access to this data. Several Web browser based technologies (XHTML/CSS/DOM/XML/XSLT and JavaScript) have matured over the last few years to the point where it is now possible to design OPeNDAP compatible Web applications with richer user interfaces than are possible with traditional Web technologies. This paper describes a Web application that takes advantage of this technology to allow interactive selection, browsing, plotting and downloading of in-situ observations from Dapper, an in-situ OPeNDAP server.</Abstract>
  <Title>DChart: A Remote Scripting Web Application for In-Situ Oceanographic Data</Title>
  <Session>IN33A</Session>
  <Hour>1340h</Hour>
  <Authors>
    <Author><Name>Sirott, J</Name><Email>sirott@sirvin.com</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2007_Fall_Meeting_IN11A-0102.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2007 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN11A-0102</Id>
  <Keywords>
    <Keyword>0525  Data management</Keyword>
    <Keyword>1890  Wetlands</Keyword>
  </Keywords>
  <Abstract>We have recently developed a wireless sensor system for environmental monitoring. The system is based upon the sensor platform by Telos, soil moisture sensors from Decagon and our own temperature sensors. The system was deployed at the Jug Bay Wetland Sanctuary, around several nests of Eastern Box Turtles (Terrapene carolina). Conditions in the soil where turtles excavate their nests can have a profound effect on egg survival, hatchling survival and on the sex of hatchling turtles. Turtles prefer nesting in sunny areas where solar radiation provides the heat source that warms the developing embryos. Our system has provided a continuous monitoring of all these parameters over a period of several months in the summer of 2007. The data show several interesting phenomena about temperature gradients in the vicinity of the turtle nests. The deployment also served  as a validation of our second generation sensor platform, which performed remarkably well.</Abstract>
  <Title>Turtle Nest Monitoring with Wireless Sensor Networks</Title>
  <Session>IN11A</Session>
  <Hour>0800h</Hour>
  <Authors>
    <Author><Name>Szlavecz, K</Name><Email>szlavecz@jhu.edu</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Terzis, A</Name><Email>terzis@jhu.edu</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Musaloiu, R</Name><Email>razvanm@cs.jhu.edu</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Liang, C</Name><Email>cliang4@cs.jhu.edu</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Cogan, J</Name><Email>joshtron@gmail.com</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Klofas, J</Name><Email>jklofas@gmail.com</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Xia, L</Name><Email>xiaxia@jhu.edu</Email><Affiliations><Affiliation>The Johns Hopkins University, Dept. of Earth and Planetary Sciences, Baltimore, MD 21218, United States</Affiliation></Affiliations></Author>
    <Author><Name>Swarth, C</Name><Email>rpswar@aacounty.org</Email><Affiliations><Affiliation>Jug Bay Wetlands Sanctuary, 1361 Wrighton Rd, Lothian, MD 20711, United States</Affiliation></Affiliations></Author>
    <Author><Name>Matthews, S</Name><Email>tortugachip@hotmail.com</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2009_Fall_Meeting_IN21B-1044.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2009 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics</Section>
  <Id>IN21B-1044</Id>
  <Keywords>
    <Keyword>INFORMATICS / Data management, preservation, rescue</Keyword>
    <Keyword>INFORMATICS / Interoperability</Keyword>
    <Keyword>INFORMATICS / Real-time and responsive information delivery</Keyword>
    <Keyword>OCEANOGRAPHY: GENERAL / Instruments and techniques</Keyword>
  </Keywords>
  <Abstract>Our shipboard data systems have been using UDP/IP broadcast datagrams for distributing real-time underway data starting on the R/V &lt;i&gt;Conrad&lt;/i&gt; in 1987 and expanding to include the &lt;i&gt;Ewing&lt;/i&gt;, &lt;i&gt;Palmer&lt;/i&gt;, &lt;i&gt;Gould&lt;/i&gt;, &lt;i&gt;Healy&lt;/i&gt; and &lt;i&gt;Langseth&lt;/i&gt; among others. This approach has many advantages including: ease of implementation; simplicity; and isolation of the clients from the real-time loggers. A number of other shipboard data systems have successfully adopted this approach. In the modern era of nearly full-time Internet connectivity for the research fleet, the ability to distribute near-real-time data to shore sites is expanding rapidly and should be done efficiently. For example, the NSF-supported Rolling Deck to Repository (R2R) and Shipboard Automated Meteorological and Oceanographic System (SAMOS) projects are jointly developing a new protocol to transfer high-frequency meteorological and surface oceanographic data from fleet vessels to a shore server for monitoring and quality control. At the same time, we are finding more sophisticated uses for real-time data at sea in addition to our own need to automate on-board real-time data quality checking. In order to facilitate these needs, we are developing a plan to migrate our data system to Multicast datagrams and add an open, standards-based discovery service so that clients connecting to our shipboard network can automatically find and use our data streams. &amp;lt;br/&amp;gt;</Abstract>
  <Title>Toward an improved distribution approach for real-time data sharing</Title>
  <Session>IN21B</Session>
  <Hour>0800h</Hour>
  <Authors>
    <Author><Name>Chayes, D N</Name><Email>dale@ldeo.columbia.edu</Email><Affiliations><Affiliation>Lamont-Doherty Earth Observatory, Palisades, NY, United States</Affiliation></Affiliations></Author>
    <Author><Name>Arko, R A</Name><Email>arko@ldeo.columbia.edu</Email><Affiliations><Affiliation>Lamont-Doherty Earth Observatory, Palisades, NY, United States</Affiliation></Affiliations></Author>
    <Author><Name>Roberts, S D</Name><Email>sroberts@ucar.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2006_Fall_Meeting_IN14A-08.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2006 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN14A-08</Id>
  <Keywords>
    <Keyword>0480  Remote sensing</Keyword>
  </Keywords>
  <Abstract>Many of the direct influences of disturbances such as fire or insects on ecosystem function are well known. In contrast, the interactions among disturbances are less well understood. In the forests of the western United States, the interaction between bark beetle outbreaks and subsequent fires is a pressing management concern for a diverse political, economic, and ecological community but the disturbance interaction is generally unknown. For example, although conventional wisdom holds that bark beetle outbreaks will increase fire risk, limited field studies suggest the opposite may be true. To our knowledge, no study has attempted to study bark beetle - fire interactions over the entire western United States. Here, using five years (2000-2004) of manually collected aerial detection survey (ADS) polygons depicting the extent of bark beetle outbreaks and five years (2001-2005) of Moderate Resolution Imaging Spectroradiometer (MODIS) 1km fire images (MOD14), we calculated the influence of bark beetle outbreaks on one-year-lagged subsequent fire occurrence across the entire western United States. We converted the ADS polygons to raster format and co-registered all imagery to the Albers Equal Area projection. We then calculated the conditional probability of fire given bark beetle presence P(fire|bark beetles presence) and the conditional probability of fire given bark beetle absence P(fire|bark beetle absence). The presence of bark beetles increased the probability of one-year-lagged subsequent fire occurrence by 17% to 115% with an average value of 65%, strongly suggesting that bark beetle outbreaks in one year will increase the risk of fire in the next year. Key words: bark beetles, fire, disturbance interaction, conditional probability</Abstract>
  <Title>Bark Beetle Outbreaks Increase Fire Probability in Western United States Forests</Title>
  <Session>IN14A</Session>
  <Hour>17:45h</Hour>
  <Authors>
    <Author><Name>Bisrat, S A</Name><Email>sabisrat@cc.usu.edu</Email><Affiliations><Affiliation>Department of Watershed Sciences, Utah State University, 5210 Old Main Hill, Logan, UT 84322 United States</Affiliation></Affiliations></Author>
    <Author><Name>White, M A</Name><Email>mikew@cc.usu.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2007_Fall_Meeting_IN32A-05.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2007 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN32A-05</Id>
  <Keywords>
    <Keyword>0820  Curriculum and laboratory design</Keyword>
    <Keyword>0845  Instructional tools</Keyword>
  </Keywords>
  <Abstract>The popularity of projects such as &#65533;Crisis in Darfur&apos; and the IPY (International Polar Year) network link show the potential of using the rich functionality of Virtual Globes for science outreach purposes.  However, the structure of outreach projects in Virtual Globes varies widely. Consider an analogy: If you pick up a science journal you immediately know where to find the contents page and what the title and cover story are meant to communicate.  That is because journals have a well defined set of norms that they follow in terms of layout and design.  Currently, science projects presented in virtual globes have, at best, weakly defined norms, there are little common structural elements beyond those imposed by the constraints of the virtual globe system.  This is not a criticism of the science community, it is to be expected since norms take time to develop for any new technology.  An example of the development of norms are pages on the web: when they first started appearing structure was unguided but over the last few years structural elements such as a left hand side navigation system and a bread crumb trail near the header have become common. In this paper I shall describe the developing norms of structure I have observed in one area of virtual globe development; Google Earth science outreach projects.  These norms include text introductions, video introductions, use of folders and overlay presentation.  I shall go on to examine how best to use these norms to build a clear and engaging outreach project and describe some cartographic best practices that we should also consider adopting as norms. I also will briefly explain why I think norms in science outreach aid creativity rather than limiting it despite the counter intuitive nature of this concept.</Abstract>
  <Title>Science Outreach in Virtual Globes; Best Practices</Title>
  <Session>IN32A</Session>
  <Hour>11:20h</Hour>
  <Authors>
    <Author><Name>Treves, R W</Name><Email>pentadij@gmail.com</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2010_Fall_Meeting_IN33C-07.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2010 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics</Section>
  <Id>IN33C-07</Id>
  <Keywords>
    <Keyword>INFORMATICS / Real-time and responsive information delivery</Keyword>
    <Keyword>INFORMATICS / Uncertainty</Keyword>
    <Keyword>SPACE WEATHER</Keyword>
    <Keyword>SPACE WEATHER / Impacts on technological systems</Keyword>
  </Keywords>
  <Abstract>The Space Vehicles Directorate of the Air Force Research Laboratory (AFRL/RVBX) and the Space Environment Division of the Space and Missile Systems Center (AFSPC SYAG/WMLE) have combined efforts to design, develop, test, implement, and validate numerical and graphical products for Air Force Space Command&amp;#8217;s (AFSPC) Space Environmental Effects Fusion System (SEEFS). These products were developed to analyze, specify, and forecast the effects of the near-earth space environment on Department of Defense weapons, navigation, communications, and surveillance systems in real/near-real time. This real-time attribute is the primary factor in allowing for actual operational product output, but it&amp;#8217;s also responsible for a variety of detrimental effects that need to be considered, researched, mitigated, or otherwise eliminated in future/upgrade product applications. This presentation will provide brief overviews of the SEEFS products, along with information and recommendations concerned with their near/real-time data acquisition and use, to include: input data requirements, inputs/outputs ownership, observation cadence, transmission/receipt links and cadence, data latency, quality control, error propagation and associated confidence level applications, and ensemble model run potentials. Validation issues related to real-time data will also be addressed, along with recommendations for new real-time data archiving that should prove operationally beneficial.</Abstract>
  <Title>Real-Time Data Use for Operational Space Weather Products</Title>
  <Session>IN33C</Session>
  <Hour>1510h</Hour>
  <Authors>
    <Author><Name>Quigley, S</Name><Email>Stephen.Quigley@hanscom.af.mil</Email><Affiliations><Affiliation>RVBXR, Air Force Research Laboratory, Hanscom AFB, MA, USA</Affiliation></Affiliations></Author>
    <Author><Name>Nobis, T E</Name><Email>timothy.nobis@rl.af.mil</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/Fall_Meeting_2005_IN44A-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>Fall Meeting 2005</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN44A-02</Id>
  <Keywords>
    <Keyword>0525  Data management</Keyword>
    <Keyword>0530  Data presentation and visualization</Keyword>
    <Keyword>3030  Micropaleontology</Keyword>
    <Keyword>4994  Instruments and techniques</Keyword>
    <Keyword>9820  Techniques applicable in three or more fields</Keyword>
  </Keywords>
  <Abstract>The use of fossils to constrain age models for geological samples is not as straightforward as it might seem. Even though index fossils have been defined as biostratigraphic time markers ambiguity arises from the synonymous use of taxonomic names.  Progress in our understanding of the origin of certain species have sometimes lead to substantial changes in the taxonomic classification of these organisms. TaxonConcept was created as part of the Stratigraphy.net initiative as a tool to manage taxonomic information and complex knowledge networks to help resolve taxonomic ambiguities in biostratigraphy. Its workflow is based on the principles of open nomenclature. Open nomenclature allows researchers to comment on the identification of a specimen which cannot exactly be determined and is frequently used in synonymy lists. The use of such synonymy lists in TaxonConcept allows to work with taxonomic classifications that are uncertain, or where several versions exist. Every single taxonomic entity in TaxonConcept is recorded with its relevant citations in the literature. This allows to manage information on taxonomy. The members of working groups using TaxonConcept can record their opinion on the taxonomic classification of each taxon in the framework of open nomenclature and annotate it in free text. This managed and structured collection of taxonomic opinions is an example of knowledge management. Taxonomic opinions are otherwise dispersed throughout  the literature, if recorded at all, and are only available to the specialist. Assembled as a collection, they represent our knowledge on the taxonomy of a certain group of organisms. In the terminology of computer science, the semantic relationships between taxonomic terms are an ontology. Open nomenclature  offers a formal framework that lends itself very well to describe the nature of the relations between taxonomic terms. The use of such synonymy lists in a taxonomic information system allows interesting search options, ranging from tracking name changes to the investigation of complex taxonomic topologies. In addition to its synonymy and literature management, TaxonConcept allows to store many other information categories such as textual descriptions (e.g. diagnoses and comments), images, bioevents and specimen and collection data. Ecological information is scheduled for a later stage of the project. Already now TaxonConcept is linked to taxon names in paleoenvironmental data of the World Data Center for Marine Environmental Sciences (WDC-MARE), interfaces to other databases are planned. WDC-MARE stores environmental, marine and geological research data and frequently uses taxon names in its parameters. By linking TaxonConcept and WDC-MARE, synonymous names can be included in queries, e.g. when researching for stable isotope data measured on microfossils. TaxonConcept is not a project on authoritative taxonomic information, but is a tool for taxonomic projects to use to find a taxonomic consensus, e.g. to define a taxonomic framework for biostratigraphic studies. Both, the project specific hierarchical classification of selected taxa, as well as a project specific selection of any other information categories is supported by TaxonConcept. The results of such a taxonomic consensus can be used to create &lt;em&gt; Fossilium Catalogus&lt;/em&gt; style summaries in various output formats which can later be used to create online or print publications.</Abstract>
  <Title>Knowledge Management in Taxonomy and Biostratigraphy using TaxonConcept Software</Title>
  <Session>IN44A</Session>
  <Hour>16:15h</Hour>
  <Authors>
    <Author><Name>Klump, J</Name><Email>jens.klump@gfz-potsdam.de</Email><Affiliations><Affiliation>GeoForschungZentrum Potsdam, Telegrafenberg A3, Potsdam, 14473  Germany</Affiliation></Affiliations></Author>
    <Author><Name>Huber, R</Name><Email>robert.huber@stratigraphy.net</Email><Affiliations><Affiliation>MARUM, Univ. Bremen, Leobener Strasse, Bremen, 28359  Germany</Affiliation></Affiliations></Author>
    <Author><Name>Goetz, S</Name><Email>stefan.goetz@bio-geo.uni-karlsruhe.de</Email></Author>
  </Authors>
</AGUAbstract>
