=== ESIPFed/lod/resources/ontology/agu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.agu.org/focus_group/essi/schema"
  targetNamespace="http://www.agu.org/focus_group/essi/schema" elementFormDefault="qualified"> 
  <xs:element name="AGUAbstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Meeting" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Section" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Id" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Keywords" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Keyword" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Abstract" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Session" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Hour" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Authors" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Author" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="Email" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Affiliations" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Affiliation" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>				
                  </xs:sequence>
                </xs:complexType>
              </xs:element>					
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ESIPFed/lod/resources/data/xml/2008_Fall_Meeting_IN23B-1092.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2008 Fall Meeting</Meeting>
  <Section>Earth and Space Informatics [IN]</Section>
  <Id>IN23B-1092</Id>
  <Keywords>
    <Keyword>0525  Data management</Keyword>
    <Keyword>0530  Data presentation and visualization</Keyword>
  </Keywords>
  <Abstract>The FLUXNET synthesis data set contains on the order of 960 site-years of sensor data from over 260 sites around the world. This is a living data set; a data update this year should add new site-years from over 200 sites. The data are the ground truth for carbon-climate studies linking models and remote sensing as well as comparative field analyses. Over 65 synthesis teams are using this data to do global and regional scale analyses. The size of the dataset makes browsing the data difficult; for example, a search of the dataset for sites with particular meteorological characteristics would require a download of the complete dataset and then running all of the data through a preliminary analysis. Synthesis studies often need additional non- sensor measurements such as root biomass, soil composition, or fire occurrence; some of these variables require detailed knowledge of the site and the science. The large number of sites makes the assembly, cleaning, and long term curation of the non-sensor data daunting; a virtual conversation between the data providers, data users, and data curators is needed. The large number of sites also makes tracking updates to the site information and communicating with site PIs difficult for synthesis study teams.</Abstract>
  <Title>Interaction Support for the Global Fluxnet Data Set</Title>
  <Session>IN23B</Session>
  <Hour>1340h</Hour>
  <Authors>
    <Author><Name>Agarwal, D</Name><Email>daagarwal@lbl.gov</Email><Affiliations><Affiliation>Berkeley Water Center, LBNL/University of California, Berkeley 1 Cyclotron Rd, MS 50B-2239, Berkeley, CA 94720, United States</Affiliation></Affiliations></Author>
    <Author><Name>Humphrey, M</Name><Email>humphrey@cs.virginia.edu</Email><Affiliations><Affiliation>School of Engineering and Applied Science, Olsson Hall 236C, 151 Engineer&apos;s Way, P.O. Box 400740 University of Virginia, Charlottesville, VA 22904, United States</Affiliation></Affiliations></Author>
    <Author><Name>Beekwilder, N</Name><Email>nfb5z@cs.virginia.edu</Email><Affiliations><Affiliation>School of Engineering and Applied Science, Olsson Hall 236C, 151 Engineer&apos;s Way, P.O. Box 400740 University of Virginia, Charlottesville, VA 22904, United States</Affiliation></Affiliations></Author>
    <Author><Name>Goode, M</Name><Email>MMGoode@lbl.gov</Email><Affiliations><Affiliation>Berkeley Water Center, LBNL/University of California, Berkeley 1 Cyclotron Rd, MS 50B-2239, Berkeley, CA 94720, United States</Affiliation></Affiliations></Author>
    <Author><Name>Jackson, K</Name><Email>krjackson@lbl.gov</Email><Affiliations><Affiliation>Berkeley Water Center, LBNL/University of California, Berkeley 1 Cyclotron Rd, MS 50B-2239, Berkeley, CA 94720, United States</Affiliation></Affiliations></Author>
    <Author><Name>Weber, R</Name><Email>rjweber@lbl.gov</Email><Affiliations><Affiliation>Berkeley Water Center, LBNL/University of California, Berkeley 1 Cyclotron Rd, MS 50B-2239, Berkeley, CA 94720, United States</Affiliation></Affiliations></Author>
    <Author><Name>van Ingen, C</Name><Email>vaningen@microsoft.com</Email><Affiliations><Affiliation>Microsoft Research, 835 Market Street, San Francisco, CA 94105, United States</Affiliation></Affiliations></Author>
    <Author><Name>Baldocchi, D</Name><Email>baldocchi@nature.berkeley.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2009_Fall_Meeting_IN11A-1044.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2009 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics</Section>
  <Id>IN11A-1044</Id>
  <Keywords>
    <Keyword>INFORMATICS / Community modeling frameworks</Keyword>
    <Keyword>INFORMATICS / Interoperability</Keyword>
    <Keyword>INFORMATICS / Metadata</Keyword>
  </Keywords>
  <Abstract>The popular programming languages Java and C# provide annotations, a form of meta-data construct. Software frameworks for web integration, web services, database access, and unit testing now take advantage of annotations to reduce the complexity of APIs and the quantity of integration code between the application and framework infrastructure. Adopting annotation features in frameworks has been observed to lead to cleaner and leaner application code. The USDA Object Modeling System (OMS) version 3.0 fully embraces the annotation approach and additionally defines a meta-data standard for components and models. In version 3.0 framework/model integration previously accomplished using API calls is now achieved using descriptive annotations. This enables the framework to provide additional functionality non-invasively such as implicit multithreading, and auto-documenting capabilities while achieving a significant reduction in the size of the model source code. Using a non-invasive methodology leads to models and modeling components with only minimal dependencies on the modeling framework. Since models and modeling components are not directly bound to framework by the use of specific APIs and/or data types they can more easily be reused both within the framework as well as outside of it. To study the effectiveness of an annotation based framework approach with other modeling frameworks, a framework-invasiveness study was conducted to evaluate the effects of framework design on model code quality. A monthly water balance model was implemented across several modeling frameworks and several software metrics were collected. The metrics selected were measures of non-invasive design methods for modeling frameworks from a software engineering perspective. It appears that the use of annotations positively impacts several software quality measures. In a next step, the PRMS model was implemented in OMS 3.0 and is currently being implemented for water supply forecasting in the western United States at the USDA NRCS National Water and Climate Center. PRMS is a component based modular precipitation-runoff model developed to evaluate the impacts of various combinations of precipitation, climate, and land use on streamflow and general basin hydrology. The new OMS 3.0 PRMS model source code is more concise and flexible as a result of using the new framework&amp;#8217;s annotation based approach. The fully annotated components are now providing information directly for (i) model assembly and building, (ii) dataflow analysis for implicit multithreading, (iii) automated and comprehensive model documentation of component dependencies, physical data properties, (iv) automated model and component testing, and (v) automated audit-traceability to account for all model resources leading to a particular simulation result. Experience to date has demonstrated the multi-purpose value of using annotations. Annotations are also a feasible and practical method to enable interoperability among models and modeling frameworks. As a prototype example, model code annotations were used to generate binding and mediation code to allow the use of OMS 3.0 model components within the OpenMI context.</Abstract>
  <Title>Use of Annotations for Component and Framework Interoperability</Title>
  <Session>IN11A</Session>
  <Hour>0800h</Hour>
  <Authors>
    <Author><Name>David, O</Name><Email>odavid@colostate.edu</Email><Affiliations><Affiliation>CSU, Fort Collins, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Lloyd, W</Name><Email>wlloyd@acm.org</Email><Affiliations><Affiliation>CSU, Fort Collins, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Carlson, J</Name><Email>jack.carlson@ars.usda.gov</Email><Affiliations><Affiliation>NRCS ITC, Fort Collins, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Leavesley, G H</Name><Email>ghleavesley@comcast.net</Email><Affiliations><Affiliation>CSU, Fort Collins, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Geter, F</Name><Email>Frank.Geter@ftc.usda.gov</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2007_Fall_Meeting_IN53B-1209.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2007 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN53B-1209</Id>
  <Keywords>
    <Keyword>2799  General or miscellaneous</Keyword>
    <Keyword>6339  System design</Keyword>
    <Keyword>7599  General or miscellaneous</Keyword>
    <Keyword>7899  General or miscellaneous</Keyword>
    <Keyword>7999  General or miscellaneous</Keyword>
  </Keywords>
  <Abstract>There are a variety of data models in the physical sciences, some of which are in overlapping domains. Each of the data models have been derived in different ways. Some have been based on formal ontologies, others on informal ontologies and others on relational schemas. An additional complication is that different international agencies have divided the physical science domains into different sub-domains leading to some confusion as to which data model to adopt. The most prevalent data models in use today are the Planetary Data System (PDS), Space Physics Archive Search and Extract (SPASE), Virtual Solar Terrestrial Observatory (VSTO), the International Virtual Observatory Alliance (IVOA) and the Global Change Master Directory (GCMD). We take a comparative look at the various data models and ask the questions: Can they be reconciled? Is it possible to have a Rosetta Model to translate between each of the models? What role can ontologies play in defining a Rosetta Model?</Abstract>
  <Title>The Rosetta Model: Can the Different Physical Science Data Models be Reconciled?</Title>
  <Session>IN53B</Session>
  <Hour>1340h</Hour>
  <Authors>
    <Author><Name>King, T A</Name><Email>tking@igpp.ucla.edu</Email><Affiliations><Affiliation>Insitute of Geophysics and Planetary Physics/UCLA, 2835 Slichter Hall, Los Angeles, CA 90095-1567, United States</Affiliation></Affiliations></Author>
    <Author><Name>McGuinness, D L</Name><Email>dlm@ksl.stanford.edu</Email><Affiliations><Affiliation>Stanford University, 353 Serra Hall, Stanford, CA 94305, United States</Affiliation></Affiliations></Author>
    <Author><Name>Walker, R J</Name><Email>rwalker@igpp.ucla.edu</Email><Affiliations><Affiliation>Insitute of Geophysics and Planetary Physics/UCLA, 2835 Slichter Hall, Los Angeles, CA 90095-1567, United States</Affiliation></Affiliations></Author>
    <Author><Name>Fox, P</Name><Email>pfox@ucar.edu</Email><Affiliations><Affiliation>UCAR, 1850 Table Mesa Drive, Boulder, CO 80305, United States</Affiliation></Affiliations></Author>
    <Author><Name>Roberts, D A</Name><Email>aaron.roberts@nasa.gov</Email><Affiliations><Affiliation>NASA/NSSDC, Code 692 NASA Goddard Space Flight Center, Greenbelt, MD 20771,</Affiliation></Affiliations></Author>
    <Author><Name>Harvey, C</Name><Email>christopher.harvey@cesr.fr</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/Fall_Meeting_2005_IN23C-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>Fall Meeting 2005</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN23C-01</Id>
  <Keywords>
    <Keyword>0520  Data analysis: algorithms and implementation</Keyword>
    <Keyword>0525  Data management</Keyword>
  </Keywords>
  <Abstract>It has been 23 years since the National Research Council&apos;s Committee on Data Management and Computation (CODMAC) published its famous list of principles for successful scientific data management that have provided the framework for modern space science data management. CODMAC outlined seven principles: 1. Scientific Involvement in all aspects of space science missions. 2. Scientific Oversight of all scientific data-management activities. 3. Data Availability - Validated data should be made available to the scientific community in a timely manner. They should include appropriate ancillary data, and complete documentation. 4. Facilities - A proper balance between cost and scientific productivity should be maintained. 5. Software - Transportable well documented software should be available to process and analyze the data. 6. Scientific Data Storage -  The data should be preserved in retrievable form. 7. Data System Funding -  Adequate data funding should be made available at the outset of missions and protected from overruns. In this paper we will review the lessons learned in trying to apply these principles to space derived data. The Planetary Data System created the concept of data curation to carry out the CODMAC principles. Data curators are scientists and technologists who work directly with the mission scientists to create data products.  The efficient application of the CODMAC  principles requires that data curators and the mission team start early in a mission to plan for data access and archiving. To build the data products the planetary discipline adopted data access and documentation standards and has adhered to them. The data curators and mission team work together to produce data products and make them available.  However even with early planning and agreement on standards the needs of the science community frequently far exceed the available resources. This is  especially true for smaller principal investigator run missions. We will argue that one way to make data systems for small missions more effective is for the data curators to provide software tools to help develop the mission data system.</Abstract>
  <Title>The Principles for Successful Scientific Data Management Revisited</Title>
  <Session>IN23C</Session>
  <Hour>13:40h</Hour>
  <Authors>
    <Author><Name>Walker, R J</Name><Email>rwalker@igpp.ucla.edu</Email><Affiliations><Affiliation>Institute of Geophysics and Planetary Physics and Department of Earth and Space Science, University of California, Los Angeles, Los Angeles, CA 90095-1567  United States</Affiliation></Affiliations></Author>
    <Author><Name>King, T A</Name><Email>tking@igpp.ucla.edu</Email><Affiliations><Affiliation>Institute of Geophysics and Planetary Physics, University of California, Los Angeles, Los Angeles, CA 90095-1567  United States</Affiliation></Affiliations></Author>
    <Author><Name>Joy, S P</Name><Email>sjoy@igpp.ucla.edu</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2009_Fall_Meeting_IN33B-1040.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2009 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics</Section>
  <Id>IN33B-1040</Id>
  <Keywords>
    <Keyword>INFORMATICS / Data assimilation, integration and fusion</Keyword>
    <Keyword>INFORMATICS / Data management, preservation, rescue</Keyword>
    <Keyword>INFORMATICS / Machine-to-machine communication</Keyword>
    <Keyword>INFORMATICS / Real-time and responsive information delivery</Keyword>
  </Keywords>
  <Abstract>NOAA, DoD, and NASA are jointly acquiring the National Polar-orbiting Operational Environmental Satellite System (NPOESS) replacing the current NOAA Polar-orbiting Operational Environmental Satellites (POES) and the DoD&apos;s Defense Meteorological Satellite Program (DMSP). The NPOESS satellites will carry a suite of sensors to collect meteorological, oceanographic, climatological, and solar-geophysical observations of the earth, atmosphere and space. The ground data processing segment is the Interface Data Processing Segment (IDPS), developed by Raytheon Intelligence &amp;amp; Information Systems (IIS). The IDPS processes NPOESS satellite data to provide environmental data products (aka, Environmental Data Records or EDRs) to US NOAA and DoD processing centers. The IDPS will process EDRs beginning with the NPOESS Preparatory Project (NPP) and through the lifetime of the NPOESS system. The command and telemetry segment is the Command, Control and Communications Segment (C3S), also developed by Raytheon IIS. C3S is responsible for managing the overall NPOESS mission from control and status of the space and ground assets to ensuring delivery of timely, high quality data from the Space Segment (SS) to IDPS for processing. In addition, the C3S provides the globally distributed ground assets necessary to collect and transport mission, telemetry, and command data between the satellites and the processing locations. The C3S provides all functions required for day-to-day commanding and state-of-health monitoring of the NPP and NPOESS satellites, and delivery of SMD to each Central IDP for data products development and transfer to System subscribers. The C3S also monitors and reports system-wide health, status and data communications with external systems and between the NPOESS segments. The NPOESS C3S and IDPS ground segments have been delivered and transitioned to operations for NPP. C3S was transitioned to operations at the NOAA Satellite Operations Facility in Suitland MD in August 2007 and IDPS in July 2009. Both segments have been involved with several compatibility tests with the NPP Satellite at the Ball Aerospace Technology Corporation (BATC) factory. The compatibility tests involved the spacecraft bus and four sensors, VIIRS, ATMS, CrIS and OMPS. The tests involved both the ground segments flowing data between the NSOF and the BATC factory and flowing data from the polar ground station located at Svalbard over high-speed links to the NSOF and the two IDPs located at NESDIS and AFWA. This presentation will describe the NPOESS ground architecture features and enhancements for the NPOESS era. They include C3S-provided space-to-ground connectivity, reliable and secure data delivery and insight and oversight of the total operation. For NPOESS, the ground segment architecture is extended to provide additional ground receptor sites to reduce data product delivery times to users. The ground segment architecture is also extended to provide delivery of additional sensor data products from sensors similar to NPP and more NPOESS sensors. This architecture is further extended from two Centrals (NESDIS and AFWA) to two additional Centrals (FNMOC and NAVO). While the ground segment architecture is extended and enhanced for NPOESS, IDPS acts as a buffer minimizing changes in how users request and receive data products.</Abstract>
  <Title>Features of the Deployed NPOESS Ground System</Title>
  <Session>IN33B</Session>
  <Hour>1340h</Hour>
  <Authors>
    <Author><Name>Smith, D</Name><Email>dcsmith@raytheon.com</Email><Affiliations><Affiliation>SEMS/NPOESS, Raytheon IIS, Aurora, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Grant, K D</Name><Email>kdgrant@raytheon.com</Email><Affiliations><Affiliation>SEMS/NPOESS, Raytheon IIS, Aurora, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Route, G</Name><Email>GPROUTE@raytheon.com</Email><Affiliations><Affiliation>SEMS/NPOESS, Raytheon IIS, Aurora, CO, United States</Affiliation></Affiliations></Author>
    <Author><Name>Heckmann, G</Name><Email>gaheckmann@raytheon.com</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2006_Fall_Meeting_IN13E-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2006 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN13E-01</Id>
  <Keywords>
    <Keyword>0300  ATMOSPHERIC COMPOSITION AND STRUCTURE</Keyword>
    <Keyword>0345  Pollution: urban and regional</Keyword>
    <Keyword>0368  Troposphere: constituent transport and chemistry</Keyword>
    <Keyword>0520  Data analysis: algorithms and implementation</Keyword>
    <Keyword>0525  Data management</Keyword>
  </Keywords>
  <Abstract>Data on atmospheric composition relevant to air quality are collected by numerous organizations through a variety of surface and based and remote sensors. The users of such data include managers, scientist and educators, also spread over the many organizations as they participate in broad programs and pursue specific projects. Emerging IS architectures, and technologies now offer the opportunity to augment the traditional end- to-end &#65533;stovepipe&apos; information systems. Standards-based data access opens the data flow for networking and leads to reuse. Modularizing data processing components encourages broader participation and software reuse by lowering the entry threshold. The use of workflow software for the creation of applications tends to at &#65533;flatten&apos; information systems by ignoring organizational boundaries. The full value of these emerging developments is hard to evaluate at this time but in principle they offer the possibilities for integrating future air quality information systems. Application examples and major impediments will be discussed.</Abstract>
  <Title>Emerging Approaches to the Integration of Autonomous Heterogeneous Air Quality Information Systems</Title>
  <Session>IN13E</Session>
  <Hour>13:40h</Hour>
  <Authors>
    <Author><Name>Husar, R B</Name><Email>rhusar@me.wustl.edu</Email><Affiliations><Affiliation>Wshington University, 1 Brookings Drive, St. Louis, MO 63130 United States</Affiliation></Affiliations></Author>
    <Author><Name>Scheffe, R</Name><Email>Scheffe.Rich@epamail.epa.gov</Email></Author>
  </Authors>
</AGUAbstract>

=== ESIPFed/lod/resources/data/xml/2007_Fall_Meeting_IN21A-0077.xml
<?xml version="1.0" encoding="UTF-8"?>
<AGUAbstract xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.agu.org/focus_group/essi/schema" xsi:schemaLocation="http://www.agu.org/focus_group/essi/schema http://www.agu.org/focus_group/essi/schema/agu.xsd">
  <Meeting>2007 Fall Meeting</Meeting>
  <Section>Earth and Space Science Informatics [IN]</Section>
  <Id>IN21A-0077</Id>
  <Keywords>
    <Keyword>0794  Instruments and techniques</Keyword>
    <Keyword>1895  Instruments and techniques: monitoring</Keyword>
    <Keyword>3394  Instruments and techniques</Keyword>
    <Keyword>4294  Instruments and techniques</Keyword>
    <Keyword>7294  Seismic instruments and networks</Keyword>
  </Keywords>
  <Abstract>The self-adaptation concept is the central piece of the control theory widely and successfully used in engineering and military systems. Such a system contains a predictor and a measurer. The predictor takes initial condition and makes an initial prediction and the measurer then measures the state of a real world phenomenon. A feedback mechanism is built in that automatically feeds the measurement back to the predictor. The predictor takes the measurement against the prediction to calculate the prediction error and adjust its internal state based on the error. Thus, the predictor learns from the error and makes a more accurate prediction in the next step. By adopting the self-adaptation concept, we proposed the Self-adaptive Earth Predictive System (SEPS) concept for enabling the dynamic coupling between the sensor web and the Earth system models. The concept treats Earth System Models (ESM) and Earth Observations (EO) as integral components of the SEPS coupled by the SEPS framework. EO measures the Earth system state while ESM predicts the evolution of the state. A feedback mechanism processes EO measurements and feeds them into ESM during model runs or as initial conditions. A  feed-forward mechanism analyzes the ESM predictions against science goals for scheduling optimized/targeted observations. The SEPS framework automates the Feedback and Feed-forward mechanisms (the FF-loop). Based on open consensus-based standards, a general SEPS framework can be developed for supporting the dynamic, interoperable coupling between ESMs and EO. Such a framework can support the plug-in-and-play capability of both ESMs and diverse sensors and data systems as long as they support the standard interfaces. This presentation discusses the SEPS concept, the service-oriented architecture (SOA) of SEPS framework, standards of choices for the framework, and the implementation. The presentation also presents examples of SEPS to demonstrate dynamic, interoperable, and live coupling of ESM with the sensor web enabled by the framework.</Abstract>
  <Title>Enabling the dynamic coupling between sensor web and Earth system models - The Self-Adaptive Earth Predictive Systems (SEPS) framework</Title>
  <Session>IN21A</Session>
  <Hour>0800h</Hour>
  <Authors>
    <Author><Name>Di, L</Name><Email>ldi@gmu.edu</Email><Affiliations><Affiliation>Center for Spatial Information Science and Systems, George Mason University, 6301 Ivy Lane, Suite 620, Greenbelt, MD 20770, United States</Affiliation></Affiliations></Author>
    <Author><Name>Yu, G</Name><Email>gyu@gmu.edu</Email><Affiliations><Affiliation>Center for Spatial Information Science and Systems, George Mason University, 6301 Ivy Lane, Suite 620, Greenbelt, MD 20770, United States</Affiliation></Affiliations></Author>
    <Author><Name>Chen, N</Name><Email>nchen3@gmu.edu</Email></Author>
  </Authors>
</AGUAbstract>
